version: "3.8"

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=web-secure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.crt:/configuration/traefik.crt
      - ./config/traefik.key:/configuration/traefik.key
      - ./config/certificates.yml:/configuration/certificates.yml
    networks:
      vpcbr:
        ipv4_address: 172.190.0.2

  app:
    container_name: indicator-search
    build: .
    image: ubuntu:22.04
    depends_on:
      - reverse-proxy
      - db
    restart: always
    labels:
      - "traefik.http.routers.app.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    volumes:
      - ./config/.env:/code/config/.env
    networks:
      vpcbr:
        ipv4_address: 172.190.0.3

  db:
    container_name: indicator-search-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - indicator_search_db:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 172.190.0.4

volumes:
  indicator_search_db:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.190.0.0/24
          gateway: 172.190.0.1
