version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - traefik

  app:
    container_name: app
    build: .
    image: ubuntu:22.04
    depends_on:
      - db
    restart: always
volumes:
  db:
    driver: local
